// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // generated from the docs folder structure
  mainSidebar: [
    {
      type: 'autogenerated', 
      dirName: '.',
    }
  ],
};

module.exports = sidebars;
